language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: i8dEFfta6+HFNjLMpRilkwhYsGVUqXPJFGSDaKYxKm+Mqf2QGgZC973alVk1l++zMWwlPLwpINzMcpF97JoX7Xs7hCYwR/JcEm6zUDepSmJCrFk0PiMnZgG6KJa9VN9HAMnPzwOdmwv7qcQDR3Ptr9zPf7gfh+BkpegXk8xfqDKNN/9R6NM7qywRKAJ0JaSaA6WTNqrK8uoqSJmf7TPw23pb/FEWHjBTUyK3XYBedZUIv0vFMsCTY+F5xeZVKQve9zQRBZre5dqpAejrvH3uXxArBgcIdbIgXMlKneoyvUKY0sPd19gUp2wgcdu/LV8B0kVeyPjrgFtU/ycHhEPUBJW1VMGY6hq5mI891MlukJDqKsSs+bPDiV/DCtrSQH+olSJmOcFDw6RA+yeZsWGMUdNHo90ho6tgj2LFY7Ijor4LYJey9LdD/U5UyZ022LIvSA/WF41Zm+3xn+xo8R6gLRiQO45Vx+O8L8R1oAOwXLdOveRfjp1yKd2S/2zlVNZ6zjR5kpxWEu7DNeS49gKgFkKne619Vz1RgY+we/LfSklioakQ9GKivfAZxODe0+CitUXctHuh1QJzSY56k5/0HLvLtWzu5/knGME7B/ostnrM43Gol2WRYGRP/jloO/6CEUNOOvtyoX9qETcH1UO4YRCcBcN/ZWHD27kAkIgasLQ=
  on:
    tags: true
